In [ ]:
"""
HW01
Chat GPT Links:
https://chatgpt.com/share/5b6af6da-1bf0-4cc2-ad99-3a31b50d19dc
https://chatgpt.com/share/6c2436b4-59c6-4397-b47b-c89f247f3176


"""
import pandas as pd

In [6]:
### Q1 
import pandas as pd
url = "https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-05/villagers.csv"
df = pd.read_csv(url)
missValCol = df.isna().sum()
missValTot = df.isna().sum().sum()
print("Missing Values in Columns")
print(missValCol)
print("Total Missing Values", missValTot)
# As We can see by the output, the data set has missing values

Missing Values in Columns
row_n           0
id              1
name            0
gender          0
species         0
birthday        0
personality     0
song           11
phrase          0
full_id         0
url             0
dtype: int64
Total Missing Values 12

In [9]:
### Q2 ** come back after chatgpt works
df.shape

df

"""
Since I was told I reached my data analysis limit for the day, I will print df and analyze 
them based on my understanding

Each Observation is a Villager in the game Animal Crossing

row_n seems to be the number of the row of the villager in game files
id is a simpified version of the villager's full_id, and seems like an abbreviated version of the name
name is the villager's name
gender is the villager's gender
species is the villager's species
Birthday is the villager's birth date in the form MM/DD
Song is the villager's favorite song or song associated with the villager
phrase is a catchphrase that the villager says 
full_id is probably what the villager is in the game files, starting with the villager-(name) 
url is a link to a picture of the villager

"""

,row_n,id,name,gender,species,birthday,personality,song,phrase,full_id,url
0,2,admiral,Admiral,male,bird,1-27,cranky,Steep Hill,aye aye,villager-admiral,https://villagerdb.com/images/villagers/thumb/...
1,3,agent-s,Agent S,female,squirrel,7-2,peppy,DJ K.K.,sidekick,villager-agent-s,https://villagerdb.com/images/villagers/thumb/...
2,4,agnes,Agnes,female,pig,4-21,uchi,K.K. House,snuffle,villager-agnes,https://villagerdb.com/images/villagers/thumb/...
3,6,al,Al,male,gorilla,10-18,lazy,Steep Hill,Ayyeeee,villager-al,https://villagerdb.com/images/villagers/thumb/...
4,7,alfonso,Alfonso,male,alligator,6-9,lazy,Forest Life,it'sa me,villager-alfonso,https://villagerdb.com/images/villagers/thumb/...
...,...,...,...,...,...,...,...,...,...,...,...
386,475,winnie,Winnie,female,horse,1-31,peppy,My Place,hay-OK,villager-winnie,https://villagerdb.com/images/villagers/thumb/...
387,477,wolfgang,Wolfgang,male,wolf,11-25,cranky,K.K. Song,snarrrl,villager-wolfgang,https://villagerdb.com/images/villagers/thumb/...
388,480,yuka,Yuka,female,koala,7-20,snooty,Soulful K.K.,tsk tsk,villager-yuka,https://villagerdb.com/images/villagers/thumb/...
389,481,zell,Zell,male,deer,6-7,smug,K.K. D&B,pronk,villager-zell,https://villagerdb.com/images/villagers/thumb/...
390,483,zucker,Zucker,male,octopus,3-8,lazy,Spring Blossoms,bloop,villager-zucker,https://villagerdb.com/images/villagers/thumb/...

In [22]:
# Q3 
print(df.describe())
df['personality'].value_counts()

### clearly with the help of CHATGPT i can look at non numeric variables

            row_n
count  391.000000
mean   239.902813
std    140.702672
min      2.000000
25%    117.500000
50%    240.000000
75%    363.500000
max    483.000000

personality
lazy      60
normal    59
cranky    55
snooty    55
jock      55
peppy     49
smug      34
uchi      24
Name: count, dtype: int64

In [24]:
# Q4
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
print(df.shape)
print(df.describe())

### Shape reports 15 columns and 891 rows 
### Desrcibe shows only numerical variables, some of which are are represented as a numerical variable but are actually
### a true/false variable(Boolean)

(891, 15)
         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

# Q5
"""
From what the chatbot says 
shape is an attriubute, not a method so no ()s and prints out the dimensions of teh DF
describe is aa method so ()s, which performs data analysis on the numerical variables of the DF
"""

# Q6
"""
Count is how much of the numerical variable is in the column
Mean is the the total/num of observations aka the average
STD is the standard deviation which is the mean distance from the mean
MIN is the lowest value
25% is Q1(Quartile 1) which is the end of the first 25% of the data sorted in order from smallest to largest
50% is Q2 aka the median which is the middle number when the data is sorted small to large(if even number of 
observations take the avg of the two middle numbers)
75% is Q3(Quartile 3) which is the end of 75% of the data sorted in order from smallest to largest
MAX is the largest observations
"""

In [8]:
#Q7
"""
df.dropna() might be peferred over using del df['col'] when for example you have a particular row you 
would like gone, or certain characteristics of a row you would like gone like a certain number of missing values
would determine if a row gets dropped or not or drop rows with any missing values or to only drop columns with missing
values

now del df['col'] might be preffered if you for example have an entire column that you know has missing rows or 
just do not want anymore.

using del df['col'] before df.dropna() could be important if you want to delete an unwanted column before trying to
remove columns with missing values

"""

import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
url2 = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df2 = pd.read_csv(url)
#Let DF be the unchanged set and DF2 be the changed set
del df2['sibsp']
df2.dropna(inplace=True)
print(df2)
print(df)

     survived  pclass     sex   age  parch     fare embarked  class    who  \
1           1       1  female  38.0      0  71.2833        C  First  woman
3           1       1  female  35.0      0  53.1000        S  First  woman
6           0       1    male  54.0      0  51.8625        S  First    man
10          1       3  female   4.0      1  16.7000        S  Third  child
11          1       1  female  58.0      0  26.5500        S  First  woman
..        ...     ...     ...   ...    ...      ...      ...    ...    ...
871         1       1  female  47.0      1  52.5542        S  First  woman
872         0       1    male  33.0      0   5.0000        S  First    man
879         1       1  female  56.0      1  83.1583        C  First  woman
887         1       1  female  19.0      0  30.0000        S  First  woman
889         1       1    male  26.0      0  30.0000        C  First    man

     adult_male deck  embark_town alive  alone
1         False    C    Cherbourg   yes  False
3         False    C  Southampton   yes  False
6          True    E  Southampton    no   True
10        False    G  Southampton   yes  False
11        False    C  Southampton   yes   True
..          ...  ...          ...   ...    ...
871       False    D  Southampton   yes  False
872        True    B  Southampton    no   True
879       False    C    Cherbourg   yes  False
887       False    B  Southampton   yes   True
889        True    C    Cherbourg   yes   True

[182 rows x 14 columns]
     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [10]:
"""
Q8

8-1

df.groupby("col1")["col2"].describe() will group column 1 values together and then it will focus on grouping these 
by column 2 and describe will provide summary statistic data on it such as mean etc.

"""
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.groupby("sex")["age"].describe()

        count       mean        std   min   25%   50%   75%   max
sex
female  261.0  27.915709  14.110146  0.75  18.0  27.0  37.0  63.0
male    453.0  30.726645  14.678201  0.42  21.0  29.0  39.0  80.0

"""
8-2
describe looks at the entire dataset and groupby looks at 2 so the values would be different\
"""

In [1]:
"""
8-3
A
"""
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df

"""
The CHATGPT Response was Better and more starightforward than the google response that didnt straight up
tell me. A simple issue but  i prefer the chatbot(a)
"""

NameError: name 'pd' is not defined

In [3]:
"""
8-3
B
"""
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanics.csv"
df = pd.read_csv(url)
df
"""
the chatbot tells me that the url is wrong but i cannot find anything on google, so (a), gives me the correct answer
so (a)
"""

HTTPError: HTTP Error 404: Not Found

In [7]:
"""
8-3 
C
"""
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)

DF.groupby("sex")["age"].describe()


"""
Again chatbot provides a clear and consiser explanation than google which is IF i can find a similar situation 
to the error so (a)

"""

NameError: name 'DF' is not defined

In [8]:
"""
8-3
D
"""
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url
                 
# chatbot tells me exact eror and how to fix it google does not have speccific solutions as the error message is vague and could mean anything

SyntaxError: incomplete input (715710067.py, line 7)

In [9]:
"""
8-3
E

"""
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.group_by("sex")["age"].describe()

"""
Google and chatbot were equally good
i found a reddit post about the exact error with the underscore
and chat once again solved  it 
"""

AttributeError: 'DataFrame' object has no attribute 'group_by'

In [12]:
"""
8-3
F
"""
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
df.groupby("sex")["age"].describe()


"""
Google does not tell me anything chat solves it again

"""

KeyError: 'Sex'

In [ ]:
"""
8-3
G

"""
import pandas as pd
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/titanic.csv"
df = pd.read_csv(url)
titanic_df.groupby(sex)["age"].describe()

"""
ChatGPT explains how i caused the error and google does not have the precision to tackle my error 
"""

"""
9

YES i have heavily relied on course textbook for this HW and chatbots,  
not much piazza but i would say the lecture helped me 
"""